# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.decision_tree_internal_subtrees import DecisionTreeInternalSubtrees  # noqa: F401,E501
from swagger_server import util


class DecisionTreeInternal(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, title: str=None, description: str=None, key: str=None, subtrees: List[DecisionTreeInternalSubtrees]=None):  # noqa: E501
        """DecisionTreeInternal - a model defined in Swagger

        :param title: The title of this DecisionTreeInternal.  # noqa: E501
        :type title: str
        :param description: The description of this DecisionTreeInternal.  # noqa: E501
        :type description: str
        :param key: The key of this DecisionTreeInternal.  # noqa: E501
        :type key: str
        :param subtrees: The subtrees of this DecisionTreeInternal.  # noqa: E501
        :type subtrees: List[DecisionTreeInternalSubtrees]
        """
        self.swagger_types = {
            'title': str,
            'description': str,
            'key': str,
            'subtrees': List[DecisionTreeInternalSubtrees]
        }

        self.attribute_map = {
            'title': 'title',
            'description': 'description',
            'key': 'key',
            'subtrees': 'subtrees'
        }
        self._title = title
        self._description = description
        self._key = key
        self._subtrees = subtrees

    @classmethod
    def from_dict(cls, dikt) -> 'DecisionTreeInternal':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DecisionTreeInternal of this DecisionTreeInternal.  # noqa: E501
        :rtype: DecisionTreeInternal
        """
        return util.deserialize_model(dikt, cls)

    @property
    def title(self) -> str:
        """Gets the title of this DecisionTreeInternal.


        :return: The title of this DecisionTreeInternal.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this DecisionTreeInternal.


        :param title: The title of this DecisionTreeInternal.
        :type title: str
        """
        if title is None:
            raise ValueError("Invalid value for `title`, must not be `None`")  # noqa: E501

        self._title = title

    @property
    def description(self) -> str:
        """Gets the description of this DecisionTreeInternal.


        :return: The description of this DecisionTreeInternal.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this DecisionTreeInternal.


        :param description: The description of this DecisionTreeInternal.
        :type description: str
        """
        if description is None:
            raise ValueError("Invalid value for `description`, must not be `None`")  # noqa: E501

        self._description = description

    @property
    def key(self) -> str:
        """Gets the key of this DecisionTreeInternal.


        :return: The key of this DecisionTreeInternal.
        :rtype: str
        """
        return self._key

    @key.setter
    def key(self, key: str):
        """Sets the key of this DecisionTreeInternal.


        :param key: The key of this DecisionTreeInternal.
        :type key: str
        """
        if key is None:
            raise ValueError("Invalid value for `key`, must not be `None`")  # noqa: E501

        self._key = key

    @property
    def subtrees(self) -> List[DecisionTreeInternalSubtrees]:
        """Gets the subtrees of this DecisionTreeInternal.


        :return: The subtrees of this DecisionTreeInternal.
        :rtype: List[DecisionTreeInternalSubtrees]
        """
        return self._subtrees

    @subtrees.setter
    def subtrees(self, subtrees: List[DecisionTreeInternalSubtrees]):
        """Sets the subtrees of this DecisionTreeInternal.


        :param subtrees: The subtrees of this DecisionTreeInternal.
        :type subtrees: List[DecisionTreeInternalSubtrees]
        """
        if subtrees is None:
            raise ValueError("Invalid value for `subtrees`, must not be `None`")  # noqa: E501

        self._subtrees = subtrees
