# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.drug import Drug  # noqa: F401,E501
from swagger_server import util


class Dosing(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, dosing_id: int=None, drug: Drug=None, dosage: int=None, units: str=None, route: str=None, compliance_source: str=None, timestamp: str=None, timestamp_precision: str=None):  # noqa: E501
        """Dosing - a model defined in Swagger

        :param dosing_id: The dosing_id of this Dosing.  # noqa: E501
        :type dosing_id: int
        :param drug: The drug of this Dosing.  # noqa: E501
        :type drug: Drug
        :param dosage: The dosage of this Dosing.  # noqa: E501
        :type dosage: int
        :param units: The units of this Dosing.  # noqa: E501
        :type units: str
        :param route: The route of this Dosing.  # noqa: E501
        :type route: str
        :param compliance_source: The compliance_source of this Dosing.  # noqa: E501
        :type compliance_source: str
        :param timestamp: The timestamp of this Dosing.  # noqa: E501
        :type timestamp: str
        :param timestamp_precision: The timestamp_precision of this Dosing.  # noqa: E501
        :type timestamp_precision: str
        """
        self.swagger_types = {
            'dosing_id': int,
            'drug': Drug,
            'dosage': int,
            'units': str,
            'route': str,
            'compliance_source': str,
            'timestamp': str,
            'timestamp_precision': str
        }

        self.attribute_map = {
            'dosing_id': 'dosingId',
            'drug': 'drug',
            'dosage': 'dosage',
            'units': 'units',
            'route': 'route',
            'compliance_source': 'complianceSource',
            'timestamp': 'timestamp',
            'timestamp_precision': 'timestampPrecision'
        }
        self._dosing_id = dosing_id
        self._drug = drug
        self._dosage = dosage
        self._units = units
        self._route = route
        self._compliance_source = compliance_source
        self._timestamp = timestamp
        self._timestamp_precision = timestamp_precision

    @classmethod
    def from_dict(cls, dikt) -> 'Dosing':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Dosing of this Dosing.  # noqa: E501
        :rtype: Dosing
        """
        return util.deserialize_model(dikt, cls)

    @property
    def dosing_id(self) -> int:
        """Gets the dosing_id of this Dosing.


        :return: The dosing_id of this Dosing.
        :rtype: int
        """
        return self._dosing_id

    @dosing_id.setter
    def dosing_id(self, dosing_id: int):
        """Sets the dosing_id of this Dosing.


        :param dosing_id: The dosing_id of this Dosing.
        :type dosing_id: int
        """

        self._dosing_id = dosing_id

    @property
    def drug(self) -> Drug:
        """Gets the drug of this Dosing.


        :return: The drug of this Dosing.
        :rtype: Drug
        """
        return self._drug

    @drug.setter
    def drug(self, drug: Drug):
        """Sets the drug of this Dosing.


        :param drug: The drug of this Dosing.
        :type drug: Drug
        """

        self._drug = drug

    @property
    def dosage(self) -> int:
        """Gets the dosage of this Dosing.


        :return: The dosage of this Dosing.
        :rtype: int
        """
        return self._dosage

    @dosage.setter
    def dosage(self, dosage: int):
        """Sets the dosage of this Dosing.


        :param dosage: The dosage of this Dosing.
        :type dosage: int
        """

        self._dosage = dosage

    @property
    def units(self) -> str:
        """Gets the units of this Dosing.


        :return: The units of this Dosing.
        :rtype: str
        """
        return self._units

    @units.setter
    def units(self, units: str):
        """Sets the units of this Dosing.


        :param units: The units of this Dosing.
        :type units: str
        """

        self._units = units

    @property
    def route(self) -> str:
        """Gets the route of this Dosing.


        :return: The route of this Dosing.
        :rtype: str
        """
        return self._route

    @route.setter
    def route(self, route: str):
        """Sets the route of this Dosing.


        :param route: The route of this Dosing.
        :type route: str
        """

        self._route = route

    @property
    def compliance_source(self) -> str:
        """Gets the compliance_source of this Dosing.


        :return: The compliance_source of this Dosing.
        :rtype: str
        """
        return self._compliance_source

    @compliance_source.setter
    def compliance_source(self, compliance_source: str):
        """Sets the compliance_source of this Dosing.


        :param compliance_source: The compliance_source of this Dosing.
        :type compliance_source: str
        """

        self._compliance_source = compliance_source

    @property
    def timestamp(self) -> str:
        """Gets the timestamp of this Dosing.


        :return: The timestamp of this Dosing.
        :rtype: str
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp: str):
        """Sets the timestamp of this Dosing.


        :param timestamp: The timestamp of this Dosing.
        :type timestamp: str
        """

        self._timestamp = timestamp

    @property
    def timestamp_precision(self) -> str:
        """Gets the timestamp_precision of this Dosing.


        :return: The timestamp_precision of this Dosing.
        :rtype: str
        """
        return self._timestamp_precision

    @timestamp_precision.setter
    def timestamp_precision(self, timestamp_precision: str):
        """Sets the timestamp_precision of this Dosing.


        :param timestamp_precision: The timestamp_precision of this Dosing.
        :type timestamp_precision: str
        """

        self._timestamp_precision = timestamp_precision
