# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Drug(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, drug_id: int=None, rxnorm: str=None, name: str=None):  # noqa: E501
        """Drug - a model defined in Swagger

        :param drug_id: The drug_id of this Drug.  # noqa: E501
        :type drug_id: int
        :param rxnorm: The rxnorm of this Drug.  # noqa: E501
        :type rxnorm: str
        :param name: The name of this Drug.  # noqa: E501
        :type name: str
        """
        self.swagger_types = {
            'drug_id': int,
            'rxnorm': str,
            'name': str
        }

        self.attribute_map = {
            'drug_id': 'drugId',
            'rxnorm': 'rxnorm',
            'name': 'name'
        }
        self._drug_id = drug_id
        self._rxnorm = rxnorm
        self._name = name

    @classmethod
    def from_dict(cls, dikt) -> 'Drug':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Drug of this Drug.  # noqa: E501
        :rtype: Drug
        """
        return util.deserialize_model(dikt, cls)

    @property
    def drug_id(self) -> int:
        """Gets the drug_id of this Drug.


        :return: The drug_id of this Drug.
        :rtype: int
        """
        return self._drug_id

    @drug_id.setter
    def drug_id(self, drug_id: int):
        """Sets the drug_id of this Drug.


        :param drug_id: The drug_id of this Drug.
        :type drug_id: int
        """

        self._drug_id = drug_id

    @property
    def rxnorm(self) -> str:
        """Gets the rxnorm of this Drug.


        :return: The rxnorm of this Drug.
        :rtype: str
        """
        return self._rxnorm

    @rxnorm.setter
    def rxnorm(self, rxnorm: str):
        """Sets the rxnorm of this Drug.


        :param rxnorm: The rxnorm of this Drug.
        :type rxnorm: str
        """

        self._rxnorm = rxnorm

    @property
    def name(self) -> str:
        """Gets the name of this Drug.


        :return: The name of this Drug.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Drug.


        :param name: The name of this Drug.
        :type name: str
        """

        self._name = name
